# Python Variables -> Names used to reference values/memory location in programming
# Variables should follow standards/conventions usually referred to Variable naming Rules
# Some rules/conventions if violated generated syntax errors while executing the python program
# Syntax error ->  These are mistakes in the source code which cause error message to be generated by the compiler
# print() function is used output values of a variables to the console


# VARIABLES

message              =           "Hello World"
# variable       assignment          values/dataType




# PRIMARY(BASIC) DATA TYPES

# String DataTypes -> The values sequence of Characters (str)

name = "Modcom Institute"
program = "Data Science"

print(type(name))
print(type(program))

# Int DataTypes -> The values contain numbers without decimal points (int)

age = 43
quantity = 10

print(type(age))
print(type(quantity))

# Float DataTypes ->The values contain numbers with decimal point values  (float)

distance = 20.3
height = 1.75
exchange_rates = 2.5

print(type(distance))
print(type(height))
print(type(exchange_rates))

# Boolean DataType  -> The values have only two instances either, True or False  (bool)

isPresent = False
access = True

print(type(isPresent))
print(type(access))








